FROM microsoft/dotnet:2.1-aspnetcore-runtime

# Set the working directory
WORKDIR /app

# Copy the app
COPY bin/Release/publish /app

EXPOSE 5000

ENV TZ=Europe/Brussels
ENV CONNECTIONSTRING=...
ENV OVERLORD_IDENTIFICATION=...

# Start the app
ENTRYPOINT ["dotnet", "HTF2018.Backend.Api.dll"]